# Generated by Django 4.2 on 2023-12-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('img', models.ImageField(upload_to='images')),
                ('bust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.author')),
            ],
        ),
    ]
