# Generated by Django 4.2 on 2023-12-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_author_bust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(default=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='password',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone',
            field=models.IntegerField(default=True),
        ),
    ]
