# Generated by Django 4.2 on 2023-12-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_task_email_alter_task_img_alter_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.task'),
        ),
    ]
