# Generated by Django 4.2 on 2023-12-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_author_bust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bust',
        ),
        migrations.AddField(
            model_name='task',
            name='bust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photos.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
