# Generated by Django 4.2 on 2023-12-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_remove_task_bust_author_bust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='email',
            new_name='emailcopy',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='img',
            new_name='imgcopy',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='namecopy',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='password',
            new_name='passwordcopy',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='phone',
            new_name='phonecopy',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bust',
        ),
    ]
