# Generated by Django 4.2 on 2023-12-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
